/*
 * App URI: app/mobile/camera
 * Source Location: app/mobile/camera.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/mobile/camera", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * camera.js
			 * Created at 2021. 4. 19. 오전 11:58:44.
			 *
			 * @author 김민규
			 ************************************************/
			
			var cordova = cpr.core.Module.require("module/cordova");
			
			/*
			 * "사진 촬영" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn1 = e.control;
				cordova.takePicture().then(function(input){
					changeImage(input);
				});;
			}
			
			
			/*
			 * "사진 선택" 버튼(btn2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn2Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn2 = e.control;
				cordova.selectPicture().then(function(input){
					changeImage(input);
				});;
			}
			
			function changeImage(url){
				var grp1 = app.lookup("grp1");
				grp1.style.css({
					"background-image": "url(" + encodeURI(url) + ")",
					"background-size" : "contain"
				});
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr"]);
			formLayout_1.setRows(["50px", "1fr", "1fr", "1fr"]);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "이미지 업로드";
			output_1.style.css({
				"text-align" : "center"
			});
			container.addChild(output_1, {
				"colIndex": 0,
				"rowIndex": 0
			});
			
			var group_1 = new cpr.controls.Container("grp2");
			// Layout
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.topMargin = "0px";
			formLayout_2.rightMargin = "0px";
			formLayout_2.bottomMargin = "0px";
			formLayout_2.leftMargin = "0px";
			formLayout_2.horizontalSpacing = "0px";
			formLayout_2.verticalSpacing = "0px";
			formLayout_2.setColumns(["1fr", "2fr", "1fr", "2fr", "1fr"]);
			formLayout_2.setRows(["1fr", "2fr", "1fr"]);
			group_1.setLayout(formLayout_2);
			(function(container){
				var button_1 = new cpr.controls.Button("btn1");
				button_1.style.css({
					"border-right-style" : "solid",
					"background-size" : "45px",
					"border-top-width" : "2px",
					"border-bottom-color" : "black",
					"border-right-width" : "2px",
					"border-left-color" : "black",
					"border-right-color" : "black",
					"background-position" : "center",
					"border-left-width" : "2px",
					"border-top-style" : "solid",
					"background-color" : "white",
					"border-radius" : "200px",
					"background-repeat" : "no-repeat",
					"border-left-style" : "solid",
					"border-bottom-width" : "2px",
					"border-top-color" : "black",
					"border-bottom-style" : "solid",
					"background-image" : "url('theme/common/images/button/camera.png')"
				});
				if(typeof onBtn1Click == "function") {
					button_1.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_1, {
					"colIndex": 1,
					"rowIndex": 1,
					"horizontalAlign": "center",
					"verticalAlign": "center",
					"width": 75,
					"height": 75
				});
				var button_2 = new cpr.controls.Button("btn2");
				button_2.style.css({
					"border-right-style" : "solid",
					"background-size" : "45px",
					"border-top-width" : "2px",
					"border-bottom-color" : "black",
					"border-right-width" : "2px",
					"border-left-color" : "black",
					"border-right-color" : "black",
					"background-position" : "center",
					"border-left-width" : "2px",
					"border-top-style" : "solid",
					"background-color" : "white",
					"border-radius" : "200px",
					"background-repeat" : "no-repeat",
					"border-left-style" : "solid",
					"border-bottom-width" : "2px",
					"border-top-color" : "black",
					"border-bottom-style" : "solid",
					"background-image" : "url('theme/common/images/button/image-gallery.png')"
				});
				if(typeof onBtn2Click == "function") {
					button_2.addEventListener("click", onBtn2Click);
				}
				container.addChild(button_2, {
					"colIndex": 3,
					"rowIndex": 1,
					"horizontalAlign": "center",
					"verticalAlign": "center",
					"width": 75,
					"height": 75
				});
			})(group_1);
			container.addChild(group_1, {
				"colIndex": 0,
				"rowIndex": 3
			});
			
			var group_2 = new cpr.controls.Container("grp1");
			group_2.style.css({
				"background-repeat" : "no-repeat",
				"background-position" : "center"
			});
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			group_2.setLayout(xYLayout_1);
			(function(container){
			})(group_2);
			container.addChild(group_2, {
				"colIndex": 0,
				"rowIndex": 1,
				"colSpan": 1,
				"rowSpan": 2
			});
		}
	});
	app.title = "camera";
	cpr.core.Platform.INSTANCE.register(app);
})();
