/*
 * App URI: app/mobile/device
 * Source Location: app/mobile/device.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/mobile/device", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * camera.js
			 * Created at 2021. 4. 19. 오전 11:58:44.
			 *
			 * @author 김민규
			 ************************************************/
			
			var cordova = cpr.core.Module.require("module/cordova");
			
			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(/* cpr.events.CEvent */ e){
				var deviceData = cordova.getDeviceData();
				
				var optModel = app.lookup("optModel");
				var optPlatform = app.lookup("optPlatform");
				var optUuid = app.lookup("optUuid");
				var optVersion = app.lookup("optVersion");
				var optManufacturer = app.lookup("optManufacturer");
				var optIsVirtual = app.lookup("optIsVirtual");
				var optSerial = app.lookup("optSerial");
				
				optModel.value = deviceData.model;
				optPlatform.value = deviceData.platform;
				optUuid.value = deviceData.uuid;
				optVersion.value = deviceData.version;
				optManufacturer.value = deviceData.manufacturer;
				optIsVirtual.value = deviceData.isVirtual;
				optSerial.value = deviceData.serial;
				
				app.getContainer().redraw();
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr"]);
			formLayout_1.setRows(["50px", "1fr", "1fr", "1fr"]);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "디바이스 정보";
			output_1.style.css({
				"text-align" : "center"
			});
			container.addChild(output_1, {
				"colIndex": 0,
				"rowIndex": 0
			});
			
			var group_1 = new cpr.controls.Container("grp1");
			// Layout
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.topMargin = "0px";
			formLayout_2.rightMargin = "0px";
			formLayout_2.bottomMargin = "0px";
			formLayout_2.leftMargin = "0px";
			formLayout_2.horizontalSpacing = "0px";
			formLayout_2.verticalSpacing = "0px";
			formLayout_2.setColumns(["100px", "1fr"]);
			formLayout_2.setRows(["30px", "30px", "30px", "30px", "30px", "30px", "30px", "1fr"]);
			formLayout_2.setRowVisible(5, false);
			group_1.setLayout(formLayout_2);
			(function(container){
				var output_2 = new cpr.controls.Output();
				output_2.value = "플랫폼";
				output_2.style.css({
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "모델";
				output_3.style.css({
					"text-align" : "center"
				});
				container.addChild(output_3, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "uuid";
				output_4.style.css({
					"text-align" : "center"
				});
				container.addChild(output_4, {
					"colIndex": 0,
					"rowIndex": 2
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "버전";
				output_5.style.css({
					"text-align" : "center"
				});
				container.addChild(output_5, {
					"colIndex": 0,
					"rowIndex": 3
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "제조사";
				output_6.style.css({
					"text-align" : "center"
				});
				container.addChild(output_6, {
					"colIndex": 0,
					"rowIndex": 4
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "가상여부";
				output_7.style.css({
					"text-align" : "center"
				});
				container.addChild(output_7, {
					"colIndex": 0,
					"rowIndex": 5
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "시리얼넘버";
				output_8.style.css({
					"text-align" : "center"
				});
				container.addChild(output_8, {
					"colIndex": 0,
					"rowIndex": 6
				});
				var output_9 = new cpr.controls.Output("optModel");
				output_9.value = "";
				container.addChild(output_9, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var output_10 = new cpr.controls.Output("optPlatform");
				output_10.value = "";
				container.addChild(output_10, {
					"colIndex": 1,
					"rowIndex": 1
				});
				var output_11 = new cpr.controls.Output("optUuid");
				output_11.value = "";
				container.addChild(output_11, {
					"colIndex": 1,
					"rowIndex": 2
				});
				var output_12 = new cpr.controls.Output("optVersion");
				output_12.value = "";
				container.addChild(output_12, {
					"colIndex": 1,
					"rowIndex": 3
				});
				var output_13 = new cpr.controls.Output("optManufacturer");
				output_13.value = "";
				container.addChild(output_13, {
					"colIndex": 1,
					"rowIndex": 4
				});
				var output_14 = new cpr.controls.Output("optIsVirtual");
				output_14.value = "";
				container.addChild(output_14, {
					"colIndex": 1,
					"rowIndex": 5
				});
				var output_15 = new cpr.controls.Output("optSerial");
				output_15.value = "";
				container.addChild(output_15, {
					"colIndex": 1,
					"rowIndex": 6
				});
			})(group_1);
			container.addChild(group_1, {
				"colIndex": 0,
				"rowIndex": 1,
				"colSpan": 1,
				"rowSpan": 3
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "device";
	cpr.core.Platform.INSTANCE.register(app);
})();
