/*
 * App URI: app/mobile/mediaPlayer
 * Source Location: app/mobile/mediaPlayer.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/mobile/mediaPlayer", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * record.js
			 * Created at 2021. 4. 19. 오후 8:38:27.
			 *
			 * @author 김민규
			 ************************************************/
			
			var cordova = cpr.core.Module.require("module/cordova");
			var src = "/android_asset/www/app/data/audio/audio_sample01.mp3";
			
			/*
			 * 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn1 = e.control;
				cordova.stopMedia();
				cordova.playMedia(src);
			}
			
			
			/*
			 * 버튼(btn2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn2Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn2 = e.control;
				cordova.stopMedia();
			}
			
			
			/*
			 * 버튼(btn3)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn3Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn3 = e.control;
				
				cordova.playMedia(src);
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr"]);
			formLayout_1.setRows(["50px", "1fr"]);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "media 재생";
			output_1.style.css({
				"border-right-style" : "solid",
				"border-top-width" : "1px",
				"border-bottom-color" : "black",
				"border-right-width" : "1px",
				"border-left-color" : "black",
				"border-right-color" : "black",
				"border-left-width" : "1px",
				"border-top-style" : "solid",
				"border-left-style" : "solid",
				"border-bottom-width" : "1px",
				"border-top-color" : "black",
				"border-bottom-style" : "solid",
				"text-align" : "center"
			});
			container.addChild(output_1, {
				"colIndex": 0,
				"rowIndex": 0
			});
			
			var group_1 = new cpr.controls.Container("grp1");
			// Layout
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.topMargin = "0px";
			formLayout_2.rightMargin = "0px";
			formLayout_2.bottomMargin = "0px";
			formLayout_2.leftMargin = "0px";
			formLayout_2.horizontalSpacing = "0px";
			formLayout_2.verticalSpacing = "0px";
			formLayout_2.setColumns(["1fr", "1fr", "1fr"]);
			formLayout_2.setRows(["1fr", "2fr", "1fr"]);
			group_1.setLayout(formLayout_2);
			(function(container){
				var button_1 = new cpr.controls.Button("btn1");
				button_1.enabled = false;
				button_1.value = "";
				button_1.style.css({
					"border-radius" : "100px",
					"background-color" : "white",
					"background-repeat" : "no-repeat",
					"background-size" : "cover",
					"background-origin" : "padding-box",
					"background-image" : "url('theme/common/images/button/right-arrow.png')"
				});
				if(typeof onBtn1Click == "function") {
					button_1.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_1, {
					"colIndex": 2,
					"rowIndex": 1,
					"horizontalAlign": "center",
					"verticalAlign": "center",
					"height": 100
				});
				var button_2 = new cpr.controls.Button("btn2");
				button_2.value = "";
				button_2.style.css({
					"border-radius" : "50px",
					"background-color" : "white",
					"background-repeat" : "no-repeat",
					"background-size" : "contain",
					"background-position" : "center",
					"background-image" : "url('theme/common/images/button/pause.png')"
				});
				if(typeof onBtn2Click == "function") {
					button_2.addEventListener("click", onBtn2Click);
				}
				container.addChild(button_2, {
					"colIndex": 1,
					"rowIndex": 1,
					"horizontalAlign": "center",
					"verticalAlign": "center",
					"height": 100
				});
				var button_3 = new cpr.controls.Button("btn3");
				button_3.value = "";
				button_3.style.css({
					"border-radius" : "50px",
					"background-color" : "white",
					"background-repeat" : "no-repeat",
					"background-size" : "contain",
					"background-position" : "center",
					"background-image" : "url('theme/common/images/button/play.png')"
				});
				if(typeof onBtn3Click == "function") {
					button_3.addEventListener("click", onBtn3Click);
				}
				container.addChild(button_3, {
					"colIndex": 0,
					"rowIndex": 1,
					"horizontalAlign": "center",
					"verticalAlign": "center",
					"height": 100
				});
			})(group_1);
			container.addChild(group_1, {
				"colIndex": 0,
				"rowIndex": 1
			});
		}
	});
	app.title = "mediaPlayer";
	cpr.core.Platform.INSTANCE.register(app);
})();
