/*
 * App URI: app/mobile/vibrator
 * Source Location: app/mobile/vibrator.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/mobile/vibrator", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * camera.js
			 * Created at 2021. 4. 19. 오전 11:58:44.
			 *
			 * @author 김민규
			 ************************************************/
			
			var cordova = cpr.core.Module.require("module/cordova");
			
			/*
			 * 버튼(btn3)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn3Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn3 = e.control;
				cordova.runVibration(1000);
			}
			
			
			/*
			 * 버튼(btn2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn2Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn2 = e.control;
				cordova.runVibration(3000);
			}
			
			
			/*
			 * 버튼(btn4)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn4Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn4 = e.control;
				cordova.runVibration(5000);
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr", "1fr", "1fr"]);
			formLayout_1.setRows(["50px", "1fr", "2fr", "1fr"]);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "진동 알림";
			output_1.style.css({
				"text-align" : "center"
			});
			container.addChild(output_1, {
				"colIndex": 0,
				"rowIndex": 0,
				"colSpan": 3,
				"rowSpan": 1
			});
			
			var button_1 = new cpr.controls.Button("btn3");
			button_1.value = "";
			button_1.style.css({
				"border-radius" : "50px",
				"background-color" : "white",
				"background-repeat" : "no-repeat",
				"background-size" : "contain",
				"background-position" : "center",
				"background-image" : "url('theme/common/images/button/numberoneinacircle_80030.png')"
			});
			if(typeof onBtn3Click == "function") {
				button_1.addEventListener("click", onBtn3Click);
			}
			container.addChild(button_1, {
				"colIndex": 0,
				"rowIndex": 2,
				"horizontalAlign": "center",
				"verticalAlign": "center",
				"height": 100
			});
			
			var button_2 = new cpr.controls.Button("btn2");
			button_2.value = "";
			button_2.style.css({
				"border-radius" : "50px",
				"background-color" : "white",
				"background-repeat" : "no-repeat",
				"background-size" : "contain",
				"background-position" : "center",
				"background-image" : "url('theme/common/images/button/numberthreeinacircle_80289.png')"
			});
			if(typeof onBtn2Click == "function") {
				button_2.addEventListener("click", onBtn2Click);
			}
			container.addChild(button_2, {
				"colIndex": 1,
				"rowIndex": 2,
				"horizontalAlign": "center",
				"verticalAlign": "center",
				"height": 100
			});
			
			var button_3 = new cpr.controls.Button("btn4");
			button_3.value = "";
			button_3.style.css({
				"border-radius" : "50px",
				"background-color" : "white",
				"background-repeat" : "no-repeat",
				"background-size" : "contain",
				"background-position" : "center",
				"background-image" : "url('theme/common/images/button/numberfiveincircularbutton_80245.png')"
			});
			if(typeof onBtn4Click == "function") {
				button_3.addEventListener("click", onBtn4Click);
			}
			container.addChild(button_3, {
				"colIndex": 2,
				"rowIndex": 2,
				"horizontalAlign": "center",
				"verticalAlign": "center",
				"height": 100
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "vibrator";
	cpr.core.Platform.INSTANCE.register(app);
})();
